id: IFFC16334
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:45:25+00:00'
last_modified: '2022-06-07T18:57:40.700466+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20317
  title: ཡུལ་སྐོར་གྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D0A2:
      image_group_id: I8LS20319
      title: ''
      total_pages: 121
      order: 1
      base_file: D0A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
