id: P003304
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:53:54.393134
source_metadata:
  id: bdr:W8LS20317
  title: ཡུལ་སྐོར་གྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    878386e79917437d893e393104b9286f:
      image_group_id: I8LS20319
      title: ''
      volume_number: 1
      total_pages: 121
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
