id: P003304
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20317
  title: ཡུལ་སྐོར་གྱི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    878386e79917437d893e393104b9286f:
      image_group_id: I8LS20319
      title: ''
      volume_number: 1
      total_pages: 121
      base_file: v001.txt
